server:
  port: 9000
logging:
  level:
#    org:
#      springframework:
#        data: TRACE
#    reactor:
#      core: TRACE
#      util: TRACE
    com:
      greglturnquist: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"

